### ISSUE TITLE
There is no dev.js in /config

### ISSUE THREAD

**Issue by macbroadcast** [ErKiran/TwitterBot#1]
hello @ErKiran ,
while I am going thru your medium post,
> Open the dev.js file and paste all four values inside it. 
https://medium.com/@kiruu1238/building-and-deploying-random-quote-twitter-bot-easy-way-dc24fdbf01d1
 i found no dev.js in the config folder ?

https://github.com/ErKiran/TwitterBot/tree/master/config

**Comment by ErKiran** [comment]
I haven't committed that files since it contains sensitive information. You can simply create this. The file should look like this 
`module.exports={
	consumer_key: 'rbcXXXXXXXXXXXXXsmxCPRP',
  	consumer_secret: 'iZXXXXXXXXXXXXXXXXXXXXXXXv7dXQw',
 	access_token_key: '1018FFFFFFFFFFFFFFFFFFFFFFFFFFG5jOm',
 	access_token_secret: 'SUllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllljxZw',
 	applicationId:'300f65rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr35a798581e97',
 	secret:'664fzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz4a290',
 	callbackUrl:'urn:ietf:wg:oauth:2.0:oob',
 	apiKey:'956555555555555555dddddddddddd'
	};`

**Comment by macbroadcast** [comment]
Thanks for your quick response, thought so but "xxing" would be fine
